name: CI/CD Frontend

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: main-aws
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Build file
        run: yarn generate 
        env: 
          NUXT_BACKEND: ${{ secrets.NUXT_BACKEND }}
          NUXT_GRAPHQL_BACKEND: ${{ secrets.NUXT_GRAPHQL_BACKEND }}
          NUXT_PUBLIC_SITE_URL: ${{ secrets.CLOUDFRONT_URL }}
      
      - name: Verify output
        run: test -d .output/public || (echo "Not found > .output/public" && exit 1)
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: .output/public
          retention-days: 1
          
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    environment: main-aws
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download production build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: .output/public
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Upload to S3
        run: aws s3 sync .output/public s3://${{ secrets.S3_BUCKET }} --delete
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 
